import type { Metadata } from "next";
import React from "react";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import Aside from "@/layout/aside";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style = {{
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <Header />

        <div style={{ display: "flex", flex: 1 }}>
          <Aside />
          <main style={{ flex: 1, padding: "2rem" }}>
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
